### ISSUE TITLE
Whitespace issue

### ISSUE THREAD

**Issue by martpie** [wankdanker/node-dank-csv#1]
Hi ! 

Thanks for this module, it works great. I'm just having a trouble, when there is a line with a whitespace (at the end of the file for example), it returns `undefined` for each value of the line. Shouldn't whitespaces be ignored ?

**Comment by wankdanker** [comment]
Hi @KeitIG,

I'm glad to hear that you have found this module useful. I'd say that yes, whitespaces should be ignored. Could you please provide example csv data that causes this issue?

Thanks!

**Comment by wankdanker** [comment]
Never-mind the example. I understand what you are talking about. I just pushed out a fix. Published as v1.0.0 on npm.

Thanks!

**Comment by martpie** [comment]
Thanks for the fix, it's working great !
